### ISSUE TITLE
Incorrect status displayed when fine dust value is 0

### ISSUE THREAD

**Issue by bunubbv** [gravitykwon/AlwaysFine#3]
수치가 1 이상일 때부터 등급을 판단하기 때문에 적절한 값을 받아오지 못해 발생하는 문제로 판단됨.

하지만 0으로 수정하면 스킨 새로고침 이후 미세먼지 값을 불러오기 전 까지 Measure의 기본값이 0이 되기에 좋음으로 나오는 버그가 있음.

 * ~~Formula로 초기 값 -1로 지정 : Measure가 Calc가 아님~~
 * ~~0 예외 처리 IfCondition을 코드 마지막에 추가 : 효과 없음~~
 * **IfCondition이 아닌 IfMatch를 사용해서 정규식 이용**

**Comment by Doiram** [comment]
Pretendard 글꼴을 고정폭 글꼴로 변경
